name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install required dependencies
        run: |
          python -m pip install flake8
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F821,F722"
          max-line-length: "120"
          path: ""
